### ISSUE TITLE
NSSDB Performance issues

### ISSUE THREAD

**Issue by simo5** [latchset/kryoptic#130]
The NSSDB is quite slow because each attrib ute is encyrpted with a key that requires PBDF2 with 10000 rounds to derive the encryption key.

NSS "solves" this by caching such keys, so we should probably do the same in nssdb/ci.rs

**Comment by Jakuje** [comment]
Just to put some perspective how slow it is compared to the default sqlitedb, here are numbers I got from pkcs11-provider testsuite running with nssdb (still work in progress):
```
 3/87 pkcs11-provider:kryoptic / setup                 OK              0.78s
 4/87 pkcs11-provider:kryoptic.nss / setup             OK             11.55s
```
It is roughly 15x slower to set up the db, which involves a lot of read and write operations from different processes.

**Comment by Jakuje** [comment]
Not sure if this is solved completely. Right now, locally I can see that the time of the pkcs11-provider setup improved slightly, but not significantly:
```
 1/87 pkcs11-provider:softokn / setup                  OK              1.04s
 3/87 pkcs11-provider:kryoptic / setup                 OK              0.76s
 4/87 pkcs11-provider:kryoptic.nss / setup             OK             10.90s
```
It always depends on the workload. Some operations are faster, but it always takes more than both sqlitedb and softokn:
```
73/87 pkcs11-provider:softokn / tlsfuzzer              OK              8.79s
75/87 pkcs11-provider:kryoptic / tlsfuzzer             OK              8.04s
76/87 pkcs11-provider:kryoptic.nss / tlsfuzzer         OK             24.51s
```
